### ISSUE TITLE
Always unauthorized 

### ISSUE THREAD

**Issue by layos** [h4kbas/nfc-reader#13]
Hi folks, I'm a complete newbie about NFC, so I'm at my first try. Please forgive my question if it is too dumb.
I got your useful lib from git and I try to use it. I can connect to my reader, handle the "card-in" event, but when I try to write a tag in block, I always get as return code "6" that means, as far as I understand, that I'm not allowed to write.
Could you please help understand why? Thank you.

**Comment by h4kbas** [comment]
Idk if I understood it correctly but If you want to write into some block first you need to authorize it, it is a process of locking that block and then writing it

**Comment by layos** [comment]
> Idk if I understood it correctly but If you want to write into some block first you need to authorize it, it is a process of locking that block and then writing it

Thank you for your answer. 
How can I lock th block before accessing it to write it? There is any helper in the library? 

What I do in my code right now is an easy:

if( nFCReader.WriteBlock("test", "5"))
 {
        MessageBox.Show("Success");
 }

I cannot find any "lock" method or something.

Thank you in advance for any further answer.

**Comment by layos** [comment]
> Idk if I understood it correctly but If you want to write into some block first you need to authorize it, it is a process of locking that block and then writing it

Thank you I just understand that it was a problem of "threads". I opened a connection in a separate thread in my UI and it was not still active when I tented to write.

**Comment by h4kbas** [comment]
Oh I see, yeah you should have a async lock kind of thing to wait it
