### ISSUE TITLE
How to get the ATR?

### ISSUE THREAD

**Issue by Richrdz** [h4kbas/nfc-reader#18]
Sir, I want to ask you about the ATR
My device is Identive CLOUD 47x0 F
I am trying to figure out your code
From my understanding,my step
1.ScardEstablishContext to create service
2.ScardListReaders get the readers
3.ScardConnect connect the card
and then i can't understand how to read the card content
I search a lot of informations but  not much help
Someone said I must get ATR that my reader can know which card I use and i can do the read and write
Can you told me about your step and  explain ?

**Comment by tomas890628** [comment]
Hello, My friend is searching for the answer for a long time.
Can you please help us, Thanks for a great help!

**Comment by h4kbas** [comment]
Has been so long since I have a look at but it could be found under card reader states.
